### ISSUE TITLE
Submit to PyPI?

### ISSUE THREAD

**Issue by ransford** [sampsyo/confit#18]
Hi!  I'd like this module to be in PyPI so I can tell people to `pip install` it.  Another guy and I are ready to volunteer some cycles to help.  Do you have a punchlist of problems to solve / things to finish before you consider confit fit to upload?

Potential minor hitch: unfortunately it looks like there's already a "confit" project in PyPI: https://pypi.python.org/pypi/confit/0.0.0

**Comment by sampsyo** [comment]
Yes! I'm all for it. It would be totally fine to publish as-is; many things are wrong with Confit, but it has settled into a nice local minimum.

Too bad that I'm now **SO ANGRY** about somebody taking the name while I dilly-dallied! Any ideas for an alternative name? `confit-config`? "Conflict?"

**Comment by ukrutt** [comment]
Yes, that's a bummer - Confit is an awesome name.  And naming things is one of the two hardest problems in computer science.  I was thinking "Confiture" at first since Confit is a way to preserve meat, and Confiture is fruit preserves...  Alas, it is also taken (by another config system, at that!)  But what about something like jam, or preserve?  (Jam is taken, but preserve isn't.)  Or what about candy (since candied fruits are really "fruit confit", according to [Wikipedia] (https://en.wikipedia.org/wiki/Confit#Fruit_confit).

(the other two hard problems are of course cache invalidation and off-by-one problems)

**Comment by ukrutt** [comment]
As a practical matter, I have forked your repo, and I created a tag/release https://github.com/ukrutt/confit/releases/tag/v0.1.0.  This way we have a stake in the sand for our project.  We then install with `pip install https://github.com/ukrutt/confit/archive/v0.1.0.zip`.  If you create a similar tag I'll delete mine :-)

**Comment by ransford** [comment]
confuse
confront
confix
confirm
confide
confess
confabulate
confact
confect

**Comment by sampsyo** [comment]
OK! I found that Confer wasn't taken. It's not a great name, but it has a low Hamming distance. I submitted the package under that name, but I didn't change the package name or the GitHub URL. Both would be totally cool to do if you're interested.

I submitted version 0.2.0 to avoid any conflicts with your tag, @ukrutt.

I've also added both of you as repo collaborators. Go crazy!

**Comment by ransford** [comment]
I would have gone with `confuse` but ohhhhhkay.  Thanks!

**Comment by sampsyo** [comment]
Ugh is it too late to change again? Confuse is pretty good, in retrospect.

**Comment by sampsyo** [comment]
OK, it's [Confuse][] now. I feel ridiculous.

[confuse]: https://pypi.python.org/pypi/confuse
